### ISSUE TITLE
Can I user the former method to evaluate my test results?

### ISSUE THREAD

**Issue by Twsschx** [taoyds/test-suite-sql-eval#4]
I want to compare with the former model, but the official website has chosen this new method.
How can I use the old method?
Because test results for the former model hasn't been renewed.
Thank you so much.

**Comment by ruiqi-zhong** [comment]
For SPIDER, SParC and CoSQL, you can try 

`--etype match` argument.

For the classical datasets, the exact set match metric is not available. 

Feel free to let me know whether this works!

**Comment by Twsschx** [comment]
Thanks. I’d like to know when I submit my model on the SPIDER leaderboard, you evaluate it using both on dev and test datasets and you will send me an email for the final results. Does this email contain all the evaluation methods such as EXACT MATCHING ACCURACY and PARTIAL MATCHING ACCURACY?

**Comment by ruiqi-zhong** [comment]
@taoyds

**Comment by taoyds** [comment]
@Twsschx We will provide results computed by both old and new evaluation methods. For the leaderboard, we will add the test suite results of some recent models, and then rank future submissions based on the test suite evaluation metric.

**Comment by Twsschx** [comment]
Thanks. It works.
