### ISSUE TITLE
submission email may be blocked, #server did not respond, re-delivering#

### ISSUE THREAD

**Issue by ZLCaesar** [taoyds/test-suite-sql-eval#5]
I used @163 mailbox to send an e-mail to the submission mailbox(tao.yu@yale.edu) last night (22:30 Beijing time), but it didn't seem to be successful. I re-sent it with QQ mailbox this morning. I don't know if you received the email.

**Comment by ruiqi-zhong** [comment]
@taoyds

**Comment by taoyds** [comment]
I successfully received some emails sent with the QQ mailbox. Please use gmail or qq mail if 163 doesn't work.
